#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
# 简化版：自动下载 Gradle wrapper jar

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DIRNAME=$(dirname "$0")

# 如果 wrapper jar 不存在，尝试从 Gradle 分布下载
JARFILE="$DIRNAME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$JARFILE" ]; then
    echo "下载 Gradle wrapper..."
    GRADLE_VERSION=$(grep "distributionUrl" "$DIRNAME/gradle/wrapper/gradle-wrapper.properties" | sed 's/.*gradle-\([0-9.]*\)-bin.zip.*/\1/')
    JAR_URL="https://raw.githubusercontent.com/gradle/gradle/v${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar"
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL -k -o "$JARFILE" "$JAR_URL" || true
    elif command -v wget >/dev/null 2>&1; then
        wget -q -O "$JARFILE" "$JAR_URL" || true
    fi
fi

if [ ! -f "$JARFILE" ]; then
    echo "错误: 无法下载 Gradle wrapper jar"
    echo "请手动下载并放置到: $JARFILE"
    exit 1
fi

exec java -classpath "$JARFILE" org.gradle.wrapper.GradleWrapperMain "$@"
